# AFTER EDITTING THIS FILE, RE-RUN DRACUT
# Ex: dracut -f --regenerate-all

# Reference:
# bcm43xx firmware not loading on boot
# https://forums.opensuse.org/t/bcm43xx-firmware-not-loading-on-boot/126026

omit_drivers+=" bcma ssb b43legacy "
