# AFTER EDITTING THIS FILE, RE-RUN DRACUT
# Ex: dracut -f --regenerate-all

#options b43 bad_frames_preempt=1
#options b43 fwpostfix=""
#options b43 hwpctl=0
#options b43 nohwcrypt=0
#options b43 hwtkip=0
#options b43 qos=1
#options b43 btcoex=1
#options b43 verbose=2
#options b43 pio=0
#options b43 allhwsupport=0

