# /usr/lib/modprobe.d/blacklist-wl.conf provided by http://elrepo.org
#
# If the in-kernel drivers continue to load, run as root:
# dracut -f /boot/initramfs-$(uname -r).img $(uname -r)

blacklist b43
blacklist b43legacy
blacklist bcm43xx
blacklist bcma
blacklist brcm80211
blacklist brcmfmac
blacklist brcmsmac
blacklist ssb
